# Generated by Django 4.1.7 on 2023-05-01 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_remove_status_is_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_frames', models.CharField(choices=[('Withframe', 'Withframe'), ('Withoutframe', 'Withoutframe'), ('Profileframe', 'Profileframe')], max_length=30)),
                ('frame_image', models.ImageField(blank=True, null=True, upload_to='frame_image/')),
            ],
        ),
    ]
