# Generated by Django 4.1.7 on 2023-05-01 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_audiovideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='forms',
            name='formno',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
