# Generated by Django 4.1.7 on 2023-05-02 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_status_is_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forms',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='form_pdf_files/'),
        ),
        migrations.AlterField(
            model_name='liccirclars',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='lic_pdf_files/'),
        ),
    ]
