# Generated by Django 4.1.7 on 2023-05-03 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_marketingcategory_premiumcalendar_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingSms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_marketingcategory', models.CharField(choices=[('Greeting', 'Greeting'), ('Recruitment', 'Recruitment'), ('General', 'General'), ('Smart Combo Children', 'Smart Combo Children'), ('Smart Combo HNI', 'Smart Combo HNI'), ('Smart Combo Retirment', 'Smart Combo Retirment')], max_length=30)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField()),
            ],
        ),
    ]
