# Generated by Django 4.1.7 on 2023-05-03 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_marketingsms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketingsms',
            name='type_of_marketingcategory',
            field=models.CharField(choices=[('Greeting SMS', 'Greeting SMS'), ('Recruitment', 'Recruitment'), ('Reminders', 'Reminders'), ('General', 'General'), ('Smart Combo Children', 'Smart Combo Children'), ('Smart Combo General', 'Smart Combo General'), ('Smart Combo HNI', 'Smart Combo HNI'), ('Smart Combo Retirement', 'Smart Combo Retirement')], max_length=30),
        ),
    ]
