# Generated by Django 4.1.7 on 2023-05-03 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_alter_marketingsms_type_of_marketingcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='liccirclars',
            name='is_frame',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='liccirclars',
            name='lic_banners',
            field=models.ImageField(blank=True, null=True, upload_to='lic_banners/'),
        ),
        migrations.AlterField(
            model_name='policydetails',
            name='type_of_insurance',
            field=models.CharField(choices=[('Life Insurance', 'Life Insurance'), ('Health Insurance', 'Health Insurance'), ('General Insurance', 'General Insurance')], max_length=30),
        ),
    ]
