# Generated by Django 4.1.7 on 2023-05-04 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_liccirclars_is_frame_liccirclars_lic_banners_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadersCorner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('type_of_leaderscategory', models.CharField(choices=[('Agency Marketing', 'Agency Marketing'), ('Appreciation', 'Appreciation'), ('Success Stories', 'Success Stories'), ('Sales Tip', 'Sales Tip'), ('Certificate', 'Certificate')], max_length=30)),
                ('is_frame', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LeadersCornerCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MixPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_MixPlanCategory', models.CharField(choices=[('Retirement', 'Retirement'), ('Children', 'Children'), ('General', 'General'), ('HNI', 'HNI')], max_length=30)),
                ('is_frame', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MixPlanCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
