# Generated by Django 4.1.7 on 2023-05-04 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_leaderscorner_leaderscornercategory_mixplan_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaderscorner',
            old_name='type_of_leaderscategory',
            new_name='leaderscategory',
        ),
        migrations.RenameField(
            model_name='marketingsms',
            old_name='type_of_marketingcategory',
            new_name='marketingcategory',
        ),
        migrations.RenameField(
            model_name='mixplan',
            old_name='type_of_MixPlanCategory',
            new_name='MixPlanCategory',
        ),
    ]
