# Generated by Django 4.1.7 on 2023-05-04 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0028_profileframe_is_frame'),
    ]

    operations = [
        migrations.CreateModel(
            name='licplans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('endownment plan', 'endownment plan'), ('money back plan', 'money back plan'), ('children single premimum plan', 'children single premimum plan'), ('term insurance plan', 'term insurance plan'), ('health plan', 'health plan'), ('pension plan', 'pension plan'), ('underwriting', 'underwriting'), ('genral', 'genral'), ('ulip', 'ulip'), ('old circulars', 'old circulars')], max_length=30)),
                ('lic_banners', models.ImageField(blank=True, null=True, upload_to='lic_banners/')),
                ('is_frame', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='liccirclars',
            name='is_frame',
        ),
        migrations.RemoveField(
            model_name='liccirclars',
            name='lic_banners',
        ),
    ]
