# Generated by Django 4.1.7 on 2023-05-04 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0030_remove_leaderscorner_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderscorner',
            name='leader_banners',
            field=models.ImageField(blank=True, null=True, upload_to='leader_banners /'),
        ),
    ]
