# Generated by Django 4.1.7 on 2023-05-04 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0031_leaderscorner_leader_banners'),
    ]

    operations = [
        migrations.AddField(
            model_name='mixplan',
            name='mixplan_banners',
            field=models.ImageField(blank=True, null=True, upload_to='mixplan_banners /'),
        ),
    ]
