# Generated by Django 4.1.7 on 2023-05-08 10:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0035_statuscategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlanCategory',
        ),
        migrations.RemoveField(
            model_name='liccirclars',
            name='type_of_category',
        ),
        migrations.AddField(
            model_name='categories',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categories',
            name='type_of_category',
            field=models.CharField(blank=True, choices=[('Hindi', 'Hindi'), ('English', 'English')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='categories',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='liccirclars',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
