# Generated by Django 4.1.7 on 2023-05-08 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0036_delete_plancategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='type_of_category',
        ),
        migrations.AddField(
            model_name='banners',
            name='type_of_banner',
            field=models.CharField(blank=True, choices=[('Hindi', 'Hindi'), ('English', 'English')], max_length=10, null=True),
        ),
    ]
