# Generated by Django 4.1.7 on 2023-04-20 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('phone_number', models.CharField(max_length=10, unique=True)),
                ('profilei_image', models.ImageField(blank=True, null=True, upload_to='profileimages/')),
                ('full_name', models.CharField(blank=True, max_length=60, null=True)),
                ('designation', models.CharField(blank=True, max_length=20, null=True)),
                ('date_of_birth', models.DateTimeField(blank=True, null=True)),
                ('date_of_joining', models.DateTimeField(blank=True, null=True)),
                ('whatsapp_mobile', models.CharField(max_length=10, unique=True)),
                ('pincode', models.CharField(max_length=6)),
                ('state', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=30)),
                ('lic_brach_number', models.CharField(max_length=10)),
                ('branch_name', models.CharField(max_length=50)),
                ('website', models.CharField(blank=True, max_length=40, null=True)),
                ('social_caption', models.CharField(max_length=4)),
                ('user_category', models.CharField(blank=True, max_length=25, null=True)),
                ('club_member', models.CharField(blank=True, max_length=30, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('is_mdrt', models.BooleanField(default=False)),
                ('business_profile', models.CharField(blank=True, max_length=20, null=True)),
                ('header_image', models.ImageField(blank=True, default='logo.jpg', null=True, upload_to='headerimages/')),
                ('otp', models.CharField(blank=True, max_length=9, null=True)),
                ('count', models.IntegerField(default=0, help_text='Number of otp sent')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdminBanners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_image', models.ImageField(upload_to='admin_banners/')),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Banners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_img', models.ImageField(blank=True, null=True, upload_to='bannerimages/')),
                ('banner_url', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.categories')),
            ],
        ),
    ]
