# Generated by Django 4.1.7 on 2023-04-29 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_newsarticals_articals_img_newsarticals_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formname', models.CharField(blank=True, max_length=50, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='pdf_files/')),
            ],
        ),
        migrations.AlterField(
            model_name='newsarticals',
            name='articals_img',
            field=models.ImageField(blank=True, null=True, upload_to='articalsimages/'),
        ),
    ]
