# Generated by Django 4.1.7 on 2023-04-29 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_forms_alter_newsarticals_articals_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forms',
            old_name='formname',
            new_name='formsname',
        ),
    ]
