# Generated by Django 4.1.7 on 2023-05-01 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_newsarticals_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='banners',
            name='is_frame',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='status',
            name='is_image',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='status',
            name='type_of_status',
            field=models.CharField(choices=[('Leaders corner', 'Leaders corner'), ('Greeting', 'Greeting'), ('Concept', 'Concept'), ('AllLC', 'AllLC'), ('Daily motivation', 'Daily motivation'), ('Sales tip', 'Sales tip'), ('AllG', 'AllG'), ('Special days', 'Special days'), ('Festivals', 'Festivals'), ('Birthday', 'Birthday'), ('Anniversary', 'Anniversary'), ('AllC', 'AllC'), ('General', 'General'), ('Retirement', 'Retirement'), ('Health', 'Health')], default='', max_length=30),
            preserve_default=False,
        ),
    ]
