# Generated by Django 4.1.7 on 2023-05-01 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_banners_is_frame_status_is_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='is_image',
        ),
    ]
