# Generated by Django 4.1.7 on 2023-05-02 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_alter_forms_formno'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='is_image',
            field=models.BooleanField(default=False),
        ),
    ]
