# Generated by Django 4.1.7 on 2023-05-02 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_alter_forms_file_alter_liccirclars_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiovideo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='frame_image/'),
        ),
    ]
