# Generated by Django 4.1.7 on 2023-05-02 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_name',
            new_name='plans_name',
        ),
    ]
