# Generated by Django 4.1.7 on 2023-05-03 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_premiumcalendar_policydetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='premiumcalendar',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
