# Generated by Django 4.1.7 on 2023-05-04 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0027_rename_type_of_leaderscategory_leaderscorner_leaderscategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileframe',
            name='is_frame',
            field=models.BooleanField(default=False),
        ),
    ]
