# Generated by Django 4.1.7 on 2023-05-04 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0032_mixplan_mixplan_banners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policydetails',
            name='type_of_insurance',
            field=models.CharField(choices=[('life insurance', 'life insurance'), ('health insurance', 'health insurance'), ('General insurance', 'General insurance')], max_length=30),
        ),
    ]
