# Generated by Django 4.1.7 on 2023-05-05 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0034_alter_policydetails_type_of_insurance'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
